### ISSUE TITLE
Use of jose.jwk and jose.jku

### ISSUE THREAD

**Issue by markkopaas** [OADA/node-jwks-utils#1]
For verifying the JWT signature, one cannot use the unverified data. Therefore we cannot use jose.jwk nor jose.jku in jwkForSignature. I propose dropping these, and leaving only jose.kid and the hint (either jwks address, jwks or jwk).

**Comment by awlayton** [comment]
I specifically plan on using `jku`, and `jwk` is in the standard. I agree `jwk` isn't all that useful unless you can verify to whom that `jwk` belongs. But when `jku` is used you know the domain associated with whoever signed the thing.

In my application just a `kid` is not enough as there is not one set of keys, but many sets.

I could maybe see reworking it so that if a hint it given, `jku` and `jwk` will not be tried. What do you think @abalmos?

**Comment by markkopaas** [comment]
But why do you need jku, if you say you have to verify the domain? why not
provide the url directly then?

Markko

**Comment by awlayton** [comment]
We get the url from `jku`, we do not know it in advance. I plan on writing a different function which checks if a known domain signed the signature.

**Comment by awlayton** [comment]
Would it not work for you to just use `#findJWK`? You tell it what the potential keys are.

**Comment by markkopaas** [comment]
I'm just trying to help you avoid making a software that is too easy to
accidentally make unsecure (by accidentally forgetting the domain check of
the jku).

I am trying to implement key rotation. Not sure yet if it will be a
preshared "jku"+jwk+x.509, using your lib, or then why not directly publish
pem files and then including the x5u in the jwt. In the latter case,
verification of the x5u domain would be mandatory, just like in your case.

**Comment by awlayton** [comment]
I agree that one could misuse this and be insecure. How do you feel about having a special value of `hint` that means look up the key from the JOSE header instead of `hint` being an optional parameter?

My application that will use this library will issue a warning when the `kid` is used or the domain in `jku` is not known, but I still want it to proceed in that case if the user wishes.

**Comment by markkopaas** [comment]
If you don't need a smooth transition from the JOSE header check to
jwk/jwks/jku, then indeed this special value could be solution, as long as
it is not the default :)

**Comment by awlayton** [comment]
How do you feel about it now @markkopaas?
